FROM python:3.10

RUN apt-get update && apt-get install -y wget \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY producer.py .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir kafka-python requests

CMD ["python", "producer.py"]
